export interface ToolSEOMeta {
  pageTitle: string;
  metaDescription: string;
  keywords: string[];
  h1: string;
  schemaName: string;
  primaryKeyword: string;
}

export const toolSEOData: Record<string, ToolSEOMeta> = {
  "pdf-to-word": {
    pageTitle: "PDF to Word Converter Online Free – Convert PDF to DOCX | QuickTools",
    metaDescription: "Convert PDF to editable Word documents online for free. Preserve formatting, text, and structure. No sign-up, no uploads – 100% browser-based PDF to Word converter.",
    keywords: ["pdf to word", "convert pdf to word", "pdf to docx online", "pdf to word free", "pdf to word converter online", "edit pdf in word", "pdf to word no upload", "pdf converter free"],
    h1: "Free PDF to Word Converter – Convert PDF to Editable DOCX Online",
    schemaName: "PDF to Word Converter – Free Online PDF to DOCX Tool",
    primaryKeyword: "pdf to word converter online free",
  },
  "pdf-compressor": {
    pageTitle: "Compress PDF Online Free – Reduce PDF File Size Without Quality Loss | QuickTools",
    metaDescription: "Compress PDF files online for free. Reduce PDF size by 40–70% without quality loss. No uploads, no sign-up. Fast browser-based PDF compressor tool.",
    keywords: ["compress pdf", "pdf compressor online", "reduce pdf size", "compress pdf online free", "pdf size reducer", "compress pdf without losing quality", "shrink pdf file", "optimize pdf online"],
    h1: "Compress PDF Online Free – Reduce PDF File Size Instantly",
    schemaName: "PDF Compressor – Compress PDF Online Free Without Quality Loss",
    primaryKeyword: "compress pdf online free",
  },
  "pdf-merge": {
    pageTitle: "Merge PDF Files Online Free – Combine Multiple PDFs Instantly | QuickTools",
    metaDescription: "Merge multiple PDF files into one document online for free. No sign-up, no uploads. Combine PDFs instantly in your browser with our free PDF merger tool.",
    keywords: ["merge pdf", "combine pdf files", "pdf merger online", "merge pdf free", "join pdf files", "pdf combiner", "merge multiple pdfs online", "combine pdfs no upload"],
    h1: "Merge PDF Files Online Free – Combine PDFs in Seconds",
    schemaName: "PDF Merger – Merge Multiple PDF Files Online Free",
    primaryKeyword: "merge pdf online free",
  },
  "pdf-split": {
    pageTitle: "Split PDF Online Free – Separate PDF Pages Instantly | QuickTools",
    metaDescription: "Split PDF documents into individual pages online for free. No uploads, no sign-up. Fast, secure, browser-based PDF splitter tool.",
    keywords: ["split pdf", "pdf splitter online", "separate pdf pages", "split pdf online free", "extract pages from pdf", "cut pdf online", "pdf page extractor", "divide pdf free"],
    h1: "Split PDF Online Free – Separate PDF Pages Instantly",
    schemaName: "PDF Splitter – Split PDF Files Online Free",
    primaryKeyword: "split pdf online free",
  },
  "pdf-to-excel": {
    pageTitle: "PDF to Excel Converter Online Free – Extract Tables from PDF | QuickTools",
    metaDescription: "Convert PDF tables to Excel or CSV format online for free. Extract data from PDFs without uploads. Free browser-based PDF to Excel converter.",
    keywords: ["pdf to excel", "pdf to csv online", "convert pdf to excel free", "extract table from pdf", "pdf to spreadsheet", "pdf data extractor", "pdf to xlsx online", "pdf table converter"],
    h1: "Convert PDF to Excel Online Free – Extract PDF Tables to Spreadsheet",
    schemaName: "PDF to Excel Converter – Extract PDF Data to CSV Online Free",
    primaryKeyword: "pdf to excel converter online free",
  },
  "ocr-pdf": {
    pageTitle: "OCR PDF Online Free – Extract Text from Scanned PDFs | QuickTools",
    metaDescription: "Extract text from scanned PDF documents using OCR technology. Convert image PDFs to searchable text online for free. No uploads required.",
    keywords: ["ocr pdf", "pdf ocr online", "extract text from pdf", "scanned pdf to text", "pdf ocr free", "pdf text extraction", "scan pdf to text", "ocr pdf no upload"],
    h1: "OCR PDF Online Free – Extract Text from Scanned PDF Documents",
    schemaName: "OCR PDF – Extract Text from Scanned PDFs Online Free",
    primaryKeyword: "ocr pdf online free",
  },
  "pdf-to-images": {
    pageTitle: "PDF to Image Converter Online Free – Convert PDF to PNG/JPG | QuickTools",
    metaDescription: "Convert PDF pages to high-quality PNG or JPEG images online for free. No uploads, instant results. Browser-based PDF to image converter.",
    keywords: ["pdf to image", "pdf to png online", "pdf to jpg converter", "convert pdf to image free", "pdf page to image", "pdf to jpeg online", "pdf image extractor", "pdf to png free"],
    h1: "Convert PDF to Images Online Free – PDF to PNG/JPG Converter",
    schemaName: "PDF to Image Converter – Convert PDF Pages to PNG/JPG Online Free",
    primaryKeyword: "pdf to image converter online free",
  },
  "pdf-to-ppt": {
    pageTitle: "PDF to PowerPoint Converter Online Free – PDF to PPT | QuickTools",
    metaDescription: "Convert PDF documents to PowerPoint presentations online for free. No uploads, no sign-up. Fast browser-based PDF to PPT converter.",
    keywords: ["pdf to ppt", "pdf to powerpoint online", "convert pdf to ppt free", "pdf to presentation", "pdf to slides", "pdf to pptx online", "pdf powerpoint converter", "pdf to ppt no upload"],
    h1: "Convert PDF to PowerPoint Online Free – PDF to PPT Converter",
    schemaName: "PDF to PowerPoint Converter – Convert PDF to PPT Online Free",
    primaryKeyword: "pdf to powerpoint converter online free",
  },
  "word-to-pdf": {
    pageTitle: "Word to PDF Converter Online Free – Convert DOCX to PDF | QuickTools",
    metaDescription: "Convert Word documents (DOCX) to PDF online for free. Preserve formatting and layout. No sign-up, no uploads – instant browser-based Word to PDF converter.",
    keywords: ["word to pdf", "docx to pdf online", "convert word to pdf free", "word to pdf converter", "doc to pdf online", "word document to pdf", "docx pdf converter", "word to pdf no upload"],
    h1: "Free Word to PDF Converter – Convert DOCX to PDF Online Instantly",
    schemaName: "Word to PDF Converter – Convert Word Documents to PDF Online Free",
    primaryKeyword: "word to pdf converter online free",
  },
  "image-to-pdf": {
    pageTitle: "Image to PDF Converter Online Free – JPG/PNG to PDF | QuickTools",
    metaDescription: "Convert JPG, PNG, and other images to PDF online for free. Merge multiple images into one PDF. No uploads, browser-based image to PDF converter.",
    keywords: ["image to pdf", "jpg to pdf online", "png to pdf converter", "convert image to pdf free", "photo to pdf", "pictures to pdf", "images to pdf online", "jpg pdf converter free"],
    h1: "Convert Images to PDF Online Free – JPG/PNG to PDF Converter",
    schemaName: "Image to PDF Converter – Convert JPG/PNG Images to PDF Online Free",
    primaryKeyword: "image to pdf converter online free",
  },
  "pdf-password-protector": {
    pageTitle: "Remove PDF Password Online Free – Unlock Protected PDF | QuickTools",
    metaDescription: "Remove password protection from PDF files online for free. Unlock encrypted PDFs instantly in your browser. No uploads, 100% secure and private.",
    keywords: ["remove pdf password", "unlock pdf online", "pdf password remover", "decrypt pdf free", "pdf unlocker online", "remove pdf encryption", "unlock protected pdf", "pdf password free"],
    h1: "Remove PDF Password Online Free – Unlock Protected PDF Documents",
    schemaName: "PDF Password Remover – Unlock PDF Files Online Free",
    primaryKeyword: "remove pdf password online free",
  },
  "image-background-remover": {
    pageTitle: "Remove Image Background Online Free – AI Background Remover | QuickTools",
    metaDescription: "Remove backgrounds from images automatically using AI. Get transparent PNG in seconds. 100% free, browser-based, no uploads – instant AI background removal.",
    keywords: ["remove background from image", "background remover online", "ai background removal", "remove image background free", "transparent background creator", "background eraser online", "photo background remover", "remove bg free"],
    h1: "Free AI Background Remover – Remove Image Background Online Instantly",
    schemaName: "Image Background Remover – AI Background Removal Online Free",
    primaryKeyword: "remove image background online free",
  },
  "image-to-webp": {
    pageTitle: "Convert Image to WebP Online Free – JPG/PNG to WebP | QuickTools",
    metaDescription: "Convert JPEG, PNG, and GIF images to WebP format online for free. Reduce image size by 30% for faster websites. Browser-based, no uploads required.",
    keywords: ["image to webp", "jpg to webp converter", "png to webp online", "convert to webp free", "webp converter online", "image webp format", "compress image to webp", "webp image converter free"],
    h1: "Convert Images to WebP Format Online Free – JPG/PNG to WebP Converter",
    schemaName: "Image to WebP Converter – Convert Images to WebP Online Free",
    primaryKeyword: "convert image to webp online free",
  },
  "image-compressor": {
    pageTitle: "Compress Images Online Free – Reduce Image Size Without Quality Loss | QuickTools",
    metaDescription: "Compress JPEG, PNG, and WebP images online for free. Reduce image file size by up to 90% without visible quality loss. No uploads, 100% browser-based.",
    keywords: ["compress image online", "image compressor free", "reduce image size", "compress jpeg online", "compress png free", "image size reducer", "optimize images online", "compress image without losing quality"],
    h1: "Compress Images Online Free – Reduce Image File Size Without Quality Loss",
    schemaName: "Image Compressor – Compress JPEG, PNG & WebP Images Online Free",
    primaryKeyword: "compress image online free",
  },
  "image-resizer": {
    pageTitle: "Resize Image Online Free – Change Image Dimensions Instantly | QuickTools",
    metaDescription: "Resize images online for free. Change width and height to any dimension. Maintain aspect ratio. Free browser-based image resizer – no uploads needed.",
    keywords: ["resize image online", "image resizer free", "change image size", "resize photo online", "image dimension changer", "resize jpg online", "scale image online", "resize picture free"],
    h1: "Resize Images Online Free – Change Image Dimensions Instantly",
    schemaName: "Image Resizer – Resize Images to Any Dimension Online Free",
    primaryKeyword: "resize image online free",
  },
  "image-cropper": {
    pageTitle: "Crop Image Online Free – Trim & Cut Images in Browser | QuickTools",
    metaDescription: "Crop images online for free. Trim photos to any size or aspect ratio. Browser-based image cropper with preset ratios for Instagram, Twitter, and more.",
    keywords: ["crop image online", "image cropper free", "crop photo online", "image trimmer online", "cut image online", "crop picture free", "photo cropper", "crop jpg online free"],
    h1: "Crop Images Online Free – Trim Photos to Any Size or Aspect Ratio",
    schemaName: "Image Cropper – Crop Photos Online Free in Browser",
    primaryKeyword: "crop image online free",
  },
  "image-to-text": {
    pageTitle: "Image to Text Converter Free – Extract Text from Images (OCR) | QuickTools",
    metaDescription: "Extract text from images online for free using OCR technology. Convert scanned images, photos, and screenshots to editable text. No uploads required.",
    keywords: ["image to text", "ocr online free", "extract text from image", "image text extractor", "photo to text converter", "ocr image online", "scan image to text", "image text recognition free"],
    h1: "Extract Text from Images Online Free – Image to Text OCR Converter",
    schemaName: "Image to Text Converter – OCR Image Text Extraction Online Free",
    primaryKeyword: "image to text converter online free",
  },
  "unit-converter": {
    pageTitle: "Unit Converter Online Free – Length, Weight, Temperature & More | QuickTools",
    metaDescription: "Convert units online for free. Length, weight, temperature, volume, speed, and more. Instant accurate conversions. Browser-based unit calculator.",
    keywords: ["unit converter", "online unit converter free", "measurement converter", "length converter", "weight converter online", "temperature converter", "metric to imperial", "unit conversion calculator"],
    h1: "Free Online Unit Converter – Convert Length, Weight, Temperature & More",
    schemaName: "Unit Converter – Free Online Measurement Conversion Tool",
    primaryKeyword: "unit converter online free",
  },
  "color-converter": {
    pageTitle: "Color Converter Online Free – HEX to RGB, HSL & More | QuickTools",
    metaDescription: "Convert colors between HEX, RGB, HSL, and CMYK formats online for free. Instant color code converter for designers and developers. No sign-up needed.",
    keywords: ["color converter", "hex to rgb converter", "rgb to hex online", "hsl color converter", "color code converter", "hex rgb hsl converter", "color format converter", "web color converter free"],
    h1: "Free Color Converter – Convert HEX, RGB, HSL & CMYK Color Codes Online",
    schemaName: "Color Converter – Free HEX, RGB, HSL Color Code Converter Online",
    primaryKeyword: "color converter online free",
  },
  "json-to-csv": {
    pageTitle: "JSON to CSV Converter Online Free – Convert JSON Data to CSV | QuickTools",
    metaDescription: "Convert JSON data to CSV format online for free. Paste JSON, download CSV instantly. Browser-based JSON to CSV converter for developers and analysts.",
    keywords: ["json to csv", "json to csv converter online", "convert json to csv free", "json csv tool", "json to excel online", "parse json to csv", "json to spreadsheet", "data converter json csv"],
    h1: "Convert JSON to CSV Online Free – Instant JSON to CSV Converter",
    schemaName: "JSON to CSV Converter – Free Online JSON to CSV Tool",
    primaryKeyword: "json to csv converter online free",
  },
  "word-counter": {
    pageTitle: "Word Counter Online Free – Count Words, Characters & Reading Time | QuickTools",
    metaDescription: "Count words, characters, sentences, and paragraphs online for free. Check reading time and speaking time. Instant browser-based word counter tool.",
    keywords: ["word counter", "word count online", "free word counter", "character counter", "count words free", "word counter tool", "online word counter", "words characters sentences counter"],
    h1: "Free Word Counter – Count Words, Characters & Reading Time Online",
    schemaName: "Word Counter – Free Online Word Count & Character Counter Tool",
    primaryKeyword: "word counter online free",
  },
  "case-converter": {
    pageTitle: "Case Converter Online Free – UPPERCASE, lowercase, Title Case | QuickTools",
    metaDescription: "Convert text case online for free. Transform text to uppercase, lowercase, title case, sentence case, camelCase, and more. Instant browser-based tool.",
    keywords: ["case converter", "text case converter online", "uppercase converter", "lowercase converter free", "title case converter", "camelcase converter", "text formatter online", "change text case free"],
    h1: "Free Case Converter – Convert Text to Uppercase, Lowercase & Title Case",
    schemaName: "Case Converter – Free Online Text Case Changer Tool",
    primaryKeyword: "case converter online free",
  },
  "text-cleaner": {
    pageTitle: "Text Cleaner Online Free – Remove Extra Spaces & Clean Text | QuickTools",
    metaDescription: "Clean and format messy text online for free. Remove extra spaces, line breaks, and formatting issues. Browser-based text cleaner – no uploads needed.",
    keywords: ["text cleaner online", "clean text free", "remove extra spaces", "text formatter online", "clean up text", "text normalizer online", "remove line breaks online", "clean copied text"],
    h1: "Free Text Cleaner – Clean & Format Messy Text Online Instantly",
    schemaName: "Text Cleaner – Free Online Text Formatting & Cleaning Tool",
    primaryKeyword: "text cleaner online free",
  },
  "text-diff": {
    pageTitle: "Text Diff Checker Free – Compare Two Texts & Find Differences | QuickTools",
    metaDescription: "Compare two text blocks and highlight differences online for free. Find additions, deletions, and changes instantly. Browser-based text diff checker.",
    keywords: ["text diff checker", "compare two texts online", "text comparison tool", "find text differences", "diff checker free", "text compare online", "document diff tool", "text difference finder"],
    h1: "Free Text Diff Checker – Compare Texts & Highlight Differences Online",
    schemaName: "Text Diff Checker – Free Online Text Comparison Tool",
    primaryKeyword: "text diff checker online free",
  },
  "html-formatter": {
    pageTitle: "HTML Formatter & Beautifier Online Free – Format HTML Code | QuickTools",
    metaDescription: "Format and beautify HTML code online for free. Indent, validate, and clean up messy HTML instantly. Browser-based HTML formatter for developers.",
    keywords: ["html formatter", "html beautifier online", "format html code free", "html code formatter", "html indentation tool", "beautify html online", "html pretty print", "html formatter free"],
    h1: "Free HTML Formatter & Beautifier – Format HTML Code Online Instantly",
    schemaName: "HTML Formatter – Free Online HTML Code Beautifier & Formatter",
    primaryKeyword: "html formatter online free",
  },
  "bmi-calculator": {
    pageTitle: "BMI Calculator Online Free – Check Your Body Mass Index | QuickTools",
    metaDescription: "Calculate your BMI (Body Mass Index) online for free. Supports metric and imperial units. Get instant BMI results with health category. Free and private.",
    keywords: ["bmi calculator", "bmi calculator online", "body mass index calculator", "free bmi calculator", "bmi metric imperial", "healthy bmi check", "bmi calculator free", "calculate bmi online"],
    h1: "Free BMI Calculator – Calculate Your Body Mass Index Online",
    schemaName: "BMI Calculator – Free Online Body Mass Index Calculator",
    primaryKeyword: "bmi calculator online free",
  },
  "age-calculator": {
    pageTitle: "Age Calculator Online Free – Calculate Your Exact Age | QuickTools",
    metaDescription: "Calculate your exact age in years, months, days, hours, and minutes online for free. Find age between any two dates. Instant browser-based age calculator.",
    keywords: ["age calculator", "calculate age online", "exact age calculator", "age in days calculator", "date difference calculator", "age calculator free", "birthday age calculator", "how old am i calculator"],
    h1: "Free Age Calculator – Calculate Your Exact Age Online in Seconds",
    schemaName: "Age Calculator – Free Online Exact Age Calculator Tool",
    primaryKeyword: "age calculator online free",
  },
  "emi-calculator": {
    pageTitle: "EMI Calculator Online Free – Calculate Loan EMI & Total Interest | QuickTools",
    metaDescription: "Calculate your loan EMI online for free. Get monthly payment, total interest, and amortization schedule instantly. Free browser-based EMI calculator.",
    keywords: ["emi calculator", "loan emi calculator", "emi calculator online free", "monthly loan payment calculator", "loan payment calculator", "mortgage emi calculator", "calculate emi online", "emi interest calculator"],
    h1: "Free EMI Calculator – Calculate Loan EMI & Total Interest Online",
    schemaName: "EMI Calculator – Free Online Loan EMI & Interest Calculator",
    primaryKeyword: "emi calculator online free",
  },
  "tip-calculator": {
    pageTitle: "Tip Calculator Online Free – Calculate Tips & Split Bills | QuickTools",
    metaDescription: "Calculate tip amount and split bills online for free. Enter bill amount, tip percentage, and number of people. Instant results. Free browser-based tool.",
    keywords: ["tip calculator", "tip calculator online", "bill splitter calculator", "calculate tip free", "restaurant tip calculator", "split bill calculator", "how much to tip", "tip percentage calculator"],
    h1: "Free Tip Calculator – Calculate Tips & Split Bills Online Instantly",
    schemaName: "Tip Calculator – Free Online Bill Tip & Splitting Calculator",
    primaryKeyword: "tip calculator online free",
  },
  "url-shortener": {
    pageTitle: "URL Shortener Online Free – Create Short Links Instantly | QuickTools",
    metaDescription: "Shorten long URLs online for free. Create short, shareable links instantly. Perfect for social media, marketing, and print materials. Free URL shortener.",
    keywords: ["url shortener", "link shortener online", "free url shortener", "shorten url free", "short link creator", "tiny url alternative", "url shortener no sign up", "link shortener free"],
    h1: "Free URL Shortener – Create Short Links Online Instantly",
    schemaName: "URL Shortener – Free Online Short Link Creator",
    primaryKeyword: "url shortener online free",
  },
  "qr-generator": {
    pageTitle: "Free QR Code Generator Online – Create QR Codes Instantly | QuickTools",
    metaDescription: "Generate QR codes for URLs, text, phone numbers, and email online for free. Download high-quality PNG instantly. No sign-up, browser-based QR generator.",
    keywords: ["qr code generator", "free qr code generator", "create qr code online", "qr code maker", "qr generator free", "online qr code creator", "generate qr code", "qr code for website"],
    h1: "Free QR Code Generator – Create QR Codes Online Instantly",
    schemaName: "QR Code Generator – Create QR Codes Online Free",
    primaryKeyword: "free qr code generator online",
  },
  "password-generator": {
    pageTitle: "Password Generator Online Free – Create Strong Secure Passwords | QuickTools",
    metaDescription: "Generate strong, secure, random passwords online for free. Customize length and character types. Cryptographically secure. No storage, 100% browser-based.",
    keywords: ["password generator", "strong password generator", "random password generator free", "secure password creator", "generate password online", "password maker free", "complex password generator", "safe password generator"],
    h1: "Free Password Generator – Create Strong, Secure Passwords Online",
    schemaName: "Password Generator – Free Online Strong Password Creator",
    primaryKeyword: "password generator online free",
  },
  "stopwatch": {
    pageTitle: "Online Stopwatch & Timer Free – Browser-Based Stopwatch | QuickTools",
    metaDescription: "Free online stopwatch and countdown timer. Lap timing, millisecond precision, and countdown alerts. Works offline. Browser-based, no download needed.",
    keywords: ["stopwatch online", "online timer free", "countdown timer", "stopwatch free", "lap timer online", "browser stopwatch", "online stopwatch no download", "timer countdown online free"],
    h1: "Free Online Stopwatch & Timer – Precise Timing in Your Browser",
    schemaName: "Online Stopwatch & Timer – Free Browser-Based Timing Tool",
    primaryKeyword: "online stopwatch free",
  },
  "random-number": {
    pageTitle: "Random Number Generator Online Free – Generate Random Numbers | QuickTools",
    metaDescription: "Generate random numbers within any range online for free. Single or multiple numbers, no repeat options. Instant browser-based random number generator.",
    keywords: ["random number generator", "random number generator online", "generate random numbers free", "random number picker", "random integer generator", "dice roll simulator", "lottery number generator", "random number free"],
    h1: "Free Random Number Generator – Generate Random Numbers Online",
    schemaName: "Random Number Generator – Free Online Random Number Tool",
    primaryKeyword: "random number generator online free",
  },
  "youtube-thumbnail-downloader": {
    pageTitle: "YouTube Thumbnail Downloader – Download HD YouTube Thumbnails Free | QuickTools",
    metaDescription: "Download YouTube video thumbnails in HD, Full HD, and maximum quality for free. Paste video URL and get thumbnail instantly. No sign-up required.",
    keywords: ["youtube thumbnail downloader", "download youtube thumbnail", "youtube thumbnail grabber", "get youtube thumbnail", "youtube thumbnail free", "hd youtube thumbnail downloader", "youtube thumbnail saver", "yt thumb downloader"],
    h1: "Free YouTube Thumbnail Downloader – Download HD Thumbnails Online",
    schemaName: "YouTube Thumbnail Downloader – Free HD YouTube Thumbnail Grabber",
    primaryKeyword: "youtube thumbnail downloader free",
  },
  "meta-tag-generator": {
    pageTitle: "Meta Tag Generator Online Free – Create SEO Meta Tags | QuickTools",
    metaDescription: "Generate SEO-optimized meta tags for your website online for free. Create title, description, Open Graph, and Twitter Card tags instantly.",
    keywords: ["meta tag generator", "seo meta tags generator", "meta description generator", "html meta tags creator", "open graph generator", "twitter card generator", "seo tags generator free", "website meta tags tool"],
    h1: "Free Meta Tag Generator – Create SEO Meta Tags for Your Website",
    schemaName: "Meta Tag Generator – Free SEO Meta Tags Creator Online",
    primaryKeyword: "meta tag generator online free",
  },
  "website-word-counter": {
    pageTitle: "Website Word Counter – Count Words on Any Website URL Free | QuickTools",
    metaDescription: "Count words on any website by URL online for free. Analyze word count, reading time, and content length of any web page. Browser-based tool.",
    keywords: ["website word counter", "count words on website", "web page word count", "url word counter", "website content analyzer", "page word count tool", "website word count free", "web page text counter"],
    h1: "Free Website Word Counter – Count Words on Any URL Online",
    schemaName: "Website Word Counter – Free Online Web Page Word Count Analyzer",
    primaryKeyword: "website word counter online free",
  },
  "base64-tool": {
    pageTitle: "Base64 Encoder Decoder Online Free – Encode & Decode Base64 | QuickTools",
    metaDescription: "Encode and decode text to/from Base64 format online for free. Instant browser-based Base64 encoder/decoder for developers. No uploads, no sign-up.",
    keywords: ["base64 encoder", "base64 decoder online", "base64 encode decode free", "base64 converter", "text to base64", "base64 to text", "base64 online tool", "base64 encoder decoder free"],
    h1: "Free Base64 Encoder & Decoder – Encode/Decode Base64 Online",
    schemaName: "Base64 Encoder Decoder – Free Online Base64 Conversion Tool",
    primaryKeyword: "base64 encoder decoder online free",
  },
};
